# Generated by Django 5.2.6 on 2025-11-26 00:54

import trade.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_product_wishlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=trade.utils.product_image_upload_path),
        ),
    ]
