# Generated by Django 5.2.6 on 2025-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', '월요일'), ('Tue', '화요일'), ('Wed', '수요일'), ('Thu', '목요일'), ('Fri', '금요일'), ('Sat', '토요일'), ('Sun', '일요일')], max_length=3),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(choices=[('중식', '중식'), ('석식', '석식')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='week_start_date',
            field=models.DateField(help_text='해당 주의 시작 날짜 (월요일 기준)', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mealitem',
            unique_together={('meal_plan', 'day_of_week', 'meal_type')},
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('아산캠퍼스', '아산캠퍼스'), ('천안캠퍼스', '천안캠퍼스')], max_length=20)),
                ('meal_type', models.CharField(choices=[('조식', '조식'), ('중식', '중식'), ('석식', '석식')], max_length=10)),
                ('date', models.DateField()),
                ('menu_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'campus', 'meal_type'],
                'unique_together': {('campus', 'meal_type', 'date')},
            },
        ),
    ]
