# Generated by Django 5.2.6 on 2025-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_alter_mealitem_day_of_week_alter_mealitem_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='campus',
            field=models.CharField(choices=[('아산', '아산'), ('영동', '영동')], max_length=20),
        ),
    ]
