# Generated by Django 5.2.6 on 2025-11-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0003_alter_dailymeal_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='meal_type',
            field=models.CharField(choices=[('중식', '중식'), ('석식', '석식')], max_length=10),
        ),
    ]
