# Generated by Django 5.2.6 on 2025-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned_notice',
            field=models.BooleanField(default=False),
        ),
    ]
